export enum Locators {
  iframe = '#storybook-preview-iframe',
  notificationComponent = '[class="nexus-notification nexus-notification-info hydrated"]>div',
  notificationComponentDefault = '[class="nexus-col-xs-4"]>nexus-notification',
  notificationIcon = '[class="nexus-notification nexus-notification-info hydrated"]>div>nexus-icon',
  notificationError = '[class="nexus-notification nexus-notification-error hydrated"]>div',
  notificationSuccess = '[class="nexus-notification nexus-notification-success hydrated"]>div',
  notificationWarning = '[class="nexus-notification nexus-notification-warning hydrated"]>div',
  notificationErrorIcon = '[class="nexus-notification nexus-notification-error hydrated"]>div>nexus-icon',
  notificationTextMessage = '[class="nexus-rhythm-4"]>nexus-card>div>div>div>nexus-card-header>nexus-notification>div>nexus-icon>svg',
  variant = '[class="css-1h8u63y"]',
  notificationCard = '[class="nexus-rhythm-4"]>nexus-card',
  notificationCardImage = '[class="nexus-rhythm-4"]>nexus-card>div>div>div>nexus-card-avatar',
  notificationCardImg = '[class="nexus-rhythm-4"]>nexus-card>div>div>div>nexus-card-avatar>img',
  notificationImageTitle = '[class="nexus-rhythm-4"]>nexus-card>div>div>div>nexus-card-header>nexus-card-header-title',
  notificationImageButton = '[class="nexus-rhythm-4"]>nexus-card>div>div>nexus-card-header-button>button>nexus-icon',
  notificationVariant = '[class="nexus-col-xs-4"]>nexus-notification>div',
  notificationVariantIcon = '[class="nexus-col-xs-4"]>nexus-notification>div>nexus-icon',
  notificationVR = '.sto-10ro1m',
  goToFullScreen = '[class="sto-102is01"]>button',
  hideAddOn = '[class="sto-l698cp"]',
  notificationOverlay = '#component-buttons-and-indicators-notification--b-overlay',
  notificationVariants = '#component-buttons-and-indicators-notification--c-variants',
  CATEGORY = '#component-buttons-and-indicators',
  COMPONENT_NAME = '#component-buttons-and-indicators-notification',
  notificationComponentLocator = '#component-buttons-and-indicators-notification',
  notificationMessageValue = 'Notification message.',
  notificationBgColorValue = 'rgba(0, 0, 0, 0)',
  infoValue = 'info',
  errorValue = 'error',
  successValue = 'success',
  warningValue = 'warning',
  falseValue = 'false',
  notificationNameValue = 'Michael Bay',
  notificationInfoText = 'Informational notification message.',
  notificationSuccessText = 'Success notification message.',
  notificationWarningText = 'Warning notification message.',
  notificationErrorText = 'Error notification message.',
}
