export enum Locators {
    iframe = '#storybook-preview-iframe',
    chipmenu = '[class="nexus-chip"]',
    chip = '[class="nexus-chip"]',
    chipButton = '[class ="nexus-row nexus-around-xs"]>nexus-chip',
    chipDisabled = '[id="control-disabled"]',
    chipError = '[name="error"]',
    chipRemovable = '[name="removable"]',
    chipEnabled = '[id="control-disabled"]',
    chipSuccess = '[name="success"]',
    chipErrorFalse = '[name="error"]',
    chipRemovableFalse = '[name="removable"]',
    chipSuccessFalse = '[name="success"]',
    chipText = '[class="css-141ccx4"]',
    chipCloseIcon = '[class="nexus-close-icon nexus-icon hydrated"]',
    chipGroup = '[class="nexus-row nexus-around-xs"]>nexus-chip-group',
    chipDefault = '[class="nexus-chip-group"]>nexus-chip',
    chipDarkTheme = '[class="nexus-theme-dark"]>nexus-chip',
    removableCheckbox = '[class="nexus-checkbox-custom"]',
    removableCheckboxInput = '[class="nexus-checkbox-input"]',
    removableCheckboxChecked = '[class="nexus-checkbox-checked-icon nexus-icon hydrated"]',
    removableCheckboxLabel = '[class="nexus-checkbox-label"]',
    removableIcon = '[data-testid="Selected Item on Chip"]',
    removableCloseIcon = '[data-testid="Selected Item on Chip"]>button>nexus-icon>svg]',
    chipVR = '.sto-10ro1m',
    chipGroupSideMenu = '#component-buttons-and-indicators-chip--b-group',
    chipDarkThemeSideMenu = '#component-buttons-and-indicators-chip--d-dark-theme',
    chipRemovableSideMenu = '#component-buttons-and-indicators-chip--e-removable',
    chipButtonError = '[class="nexus-chip-group"]>nexus-chip',
    CATEGORY = '#component-buttons-and-indicators',
    COMPONENT_NAME = '#component-buttons-and-indicators-chip',
    chipComponentLocator = '#component-buttons-and-indicators-chip',
    chipVariantSideMenu = '#component-buttons-and-indicators-chip--c-variant',
    chipErrorLocator = 'Failure',
    chipSuccessLocator = 'Success',
    chipTextValue = 'Chip Text',
    chipOnDarkThemeValue = 'Chip on  Theme',
    itemValueLocator = 'Item - 1',
    falseValue = 'false',
    trueValue = 'true',
    defaultValue = 'Default',
    disabledValue = 'Disabled',
    errorValue = 'Failure',
    successValue = 'Success',
    chipSampleValue = 'Chip Sample Text',
    chipOneValue = 'Chip - 1',
    chipTwoValue = 'Chip - 2',
    chipThreeValue = 'Chip - 3',
    blackColorValue = 'rgb(45, 46, 47)',
    redColorValue = 'rgb(218, 53, 16)',
    whiteColorValue = 'rgb(255, 255, 255)',
    greenColorValue = 'rgb(89, 209, 89)'
  }
