export enum Locators {
    iframe = '#storybook-preview-iframe',
    button = '[class="nexus-center-xs nexus-mt-5"]',
    buttonVR = '.sto-10ro1m',
    buttonComponent = '[class="nexus-btn"]',
    buttonIndicators = '[class="sidebar-item sto-8skhtv"]',
    buttonMenu = '[class="sidebar-item sto-1y7hsit"]',
    sections = '.sto-ohbggj',
    mediumButton = '[class="nexus-btn nexus-btn-medium"]',
    largeButton = '[class="nexus-btn nexus-btn-primary nexus-btn-large"]',
    fluidButton = '[data-testid="nexus-button-primary"]',
    defaultButton = '[data-testid="btnVariantDefault"]',
    primaryButton = '[class="nexus-btn-primary nexus-mt-2"]',
    warnButton = '[class="nexus-btn-warn nexus-mt-2"]',
    link = '[class="nexus-link"]',
    linkButton = '[class="nexus-col-xs-4 nexus-col-md-4 nexus-col-lg-2 nexus-mt-3"]>a',
    darkThemeDefault = '[data-testid="button-theme-dark-default"]',
    darkThemePrimary = '[class="nexus-btn nexus-btn-primary nexus-ml-2 nexus-mr-2"]',
    darkThemeDanger = '[class="nexus-btn nexus-btn-warn nexus-ml-2 nexus-mr-2"]',
    darkThemeLink = '[class="nexus-link nexus-ml-2 nexus-mr-2"]',
    disabledButton = '[class="nexus-btn nexus-btn-large nexus-btn-primary"]',
    settingsIcon = '[class="nexus-btn-icon"]',
    settingsFloatingIcon = '[class="nexus-fab"]',
    onButton = '[class="nexus-center-xs nexus-mt-3"]>button',
    onButtonSize = '[class="nexus-center-xs nexus-mt-3"]>button>nexus-icon',
    offButton = '[class="nexus-center-xs nexus-mt-3"]>button[class="nexus-btn nexus-btn-medium nexus-overline"]',
    hideButton = '[class="nexus-center-xs nexus-mt-2"]>button',
    hideButtonSize = '[class="nexus-center-xs nexus-mt-2"]>button>nexus-icon',
    buttonComponentLocator = '#component-buttons-and-indicators-button',
    CATEGORY = '[id="component-buttons-and-indicators"]',
    COMPONENT_NAME = '#component-buttons-and-indicators-button',
    buttonSizeSideMenu = '#component-buttons-and-indicators-button--b-size',
    buttonStateSideMenu = '#component-buttons-and-indicators-button--c-state',
    darkThemeSideMenu = '#component-buttons-and-indicators-button--d-dark-theme',
    disabledSideMenu = '#component-buttons-and-indicators-button--e-disabled',
    floatingSideMenu = '#component-buttons-and-indicators-button--f-floating-button',
    tabbedSideMenu = '#component-buttons-and-indicators-button--g-tabbed',
    clickMeValue = 'Click Me!',
    mediumButtonValue = 'Medium Button',
    largeButtonValue = 'Large Button',
    fluidButtonValue = 'Fluid button can hold larger text content.',
    linkValue = 'Link',
    defaultValue = 'Default',
    primaryValue = 'Primary',
    warnValue = 'Warn',
    dangerValue = 'Danger',
    settingsValue = 'Settings',
    disabledButtonValue = 'Disabled Button',
    sizeValue = 'md',
    showValue = 'Show',
    hideValue = 'Hide',
    onValue = 'On',
    offValue = 'Off',
    blackColorValue = 'rgba(0, 0, 0, 0)',
    blackVariantColorValue = 'rgb(72, 74, 76)',
    redColorValue = 'rgb(218, 53, 16)',
    whiteColorValue = 'rgb(255, 255, 255)',
    greyColorValue = 'rgb(189, 191, 193)',
    greenColorValue = 'rgb(68, 171, 70)'
}
