export enum Locators {
    iframe = '#storybook-preview-iframe',
    toastVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-popup-and-modals',
    COMPONENT_NAME = '#component-popup-and-modals-toast',
    toastComponentLocator = '#component-popup-and-modals-toast--a-toast',
    toastSideMenu = '#component-popup-and-modals-toast--a-toast',
    toastVariantsSideMenu = '#component-popup-and-modals-toast--b-variants',
    toastAutoCloseSideMenu = '#component-popup-and-modals-toast--c-auto-close',
    toastComponent = '[id="toastdefault"]',
    closeableAttribute = 'closeable',
    showAttribute = 'show',
    variantAttribute = 'variant',
    closeableValue = 'false',
    showValue = 'true',
    variantValue = 'info',
    toastIcon = '[class="nexus"]>section>nexus-toast>div>nexus-icon',
    defaultMessage = 'Default Message',
    autocloseTextbox = '[id="control-autoClose"]',
    autocloseToggle = '[id="control-closeable"]',
    iconsrc = '[id="control-iconSrc"]',
    iconPosition = '[id="control-position"]',
    chooseOptions = 'Choose option...',
    bottomOption = 'bottom',
    topOption = 'top',
    controlShow = '[id="control-show"]',
    controlVariant = '[id="control-variant"]',
    customOption = 'custom',
    errorOption = 'error',
    infoOption = 'info',
    successOption = 'success',
    warningOption = 'warning',
    toastVariants =  '[class="nexus"]>section>div>div>nexus-toast',
    toastIcons =  '[class="nexus"]>section>div>div>nexus-toast>div>nexus-icon',
    variantOneMessage = 'This is usually used to give info for users. This can be messages like availability of new feature or welcome note etc.',
    variantTwoMessage = 'The error messages such as site-maintenance or application issues can be notified with using "error" variant.',
    variantThreeMessage = 'Used to denote successful transactions or positive messages.',
    variantFourMessage = 'These are used when we want to notify users messages like password expiry or renewal of membership etc.',
    variantFiveMessage = 'Custom icons with notification messages can be created with "custom" variant.',
    reloadPageButton = '[class="nexus"]>section>button',
    reloadPage = 'Reload the page',
    autoCloseMessage = '[id="nexus-toast-auto-close"]',
    autoCloseAttribute = 'auto-close',
    autoCloseValue = '23000'
}
