export enum Locators {
    iframe = '#storybook-preview-iframe',
    breadcrumbVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-navigation',
    COMPONENT_NAME = '#component-navigation-breadcrumb',
    breadcrumbComponentLocator = '#component-navigation-breadcrumb--a-breadcrumb',
    breadcrumbSideMenu = '#component-navigation-breadcrumb--a-breadcrumb',
    disabledSideMenu = '#component-navigation-breadcrumb--b-disabled',
    withIconSideMenu = '#component-navigation-breadcrumb--c-with-icon',
    breadcrumbComponent = '[class ="nexus"]>div>nexus-breadcrumb>ol',
    breadcrumbSeperator = '[class ="nexus"]>div>nexus-breadcrumb>ol>nexus-breadcrumb-item>li>span',
    breadcrumbIndividual = '[class ="nexus"]>div>nexus-breadcrumb>ol>nexus-breadcrumb-item>li>a',
    disabledAttribute = 'disabled',
    disabledBreadCrumbItem = '[class ="nexus"]>div>nexus-breadcrumb>ol>nexus-breadcrumb-item',
    seperatorTextbox = '[id="control-separator"]',
    iconList = '[class ="nexus"]>nexus-breadcrumb>ol',
    iconSeperator = '[class ="nexus"]>nexus-breadcrumb>ol>nexus-breadcrumb>ol>nexus-breadcrumb-item>li>span',
    icons = '[class ="nexus"]>nexus-breadcrumb>ol>nexus-breadcrumb>ol>nexus-breadcrumb-item>li>nexus-icon',
    breadCrumbOne = 'Breadcrumb 1',
    breadCrumbTwo = 'Breadcrumb 2',
    breadCrumbThree = 'Breadcrumb 3',
    breadcrumb = 'Breadcrumb',
    dimensionLabel = 'Dimension',
    settingsLabel = 'Settings',
    buildLabel = 'Build',
}
