export enum Locators {
    iframe = '#storybook-preview-iframe',
    textareaLabel = '[class="nexus"]>div>nexus-form-field>nexus-label>label',
    textareaComponent = '[class="nexus"]>div>nexus-form-field>nexus-textarea',
    textareaComponentTextArea = '[class="nexus-textarea"]',
    controlAttrId = '[name="attrId"]',
    controlLabel = '[name="label"]',
    controlcols = '[name="cols"]',
    controlDisabled = '[name="disabled"]',
    controlMaxlength = '[name="maxLength"]',
    controlMinlength = '[name="minLength"]',
    controlPlaceholder = '[name="placeholder"]',
    controlValue = '[name="value"]',
    controlRows = '[name="rows"]',
    textareaVR = '[class="sto-u3ub1n"]',
    MobileTab = '[class="sto-4t3mb0"]>button',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-textarea--a-textarea',
    textareaComponentLocator = '#component-form-elements-textarea--a-textarea',
    numericValue = 'numeric',
    alphabetValue = 'alphabet',
    lowerCaseValue = 'lowerCase',
    upperCaseValue = 'upperCase',
    alphanumericValue = 'alphanumeric',
    specialCharactersValue = 'specialCharacters',
    minValue = 'minimum Value',
    maxValue = 'maximum value',
    numericVariantValue = '123567890',
    alphabetInputValue = 'abcdefghijabcdefghij',
    upperCaseInputValue = 'CAPITALLETTERS',
    alphanumericInputValue = 'abcdef1234',
    specialCharacterInputValue = '!@#$%^&*()_-+=|;:\'<,',
    numericCombinationInput = '123567890',
    singleValue = 'a',
    numericValueCombination = '123567890123567890',
    disabledValue = 'disabled',
    maxLengthValue = 'maxlength',
    minLengthValue = 'minlength',
    requiredValue = 'required',
    rowsValue = 'rows',
    colsValue = 'cols',
    nullValue = 'NaN',
    minLengthValues = '0',
    falseValue = 'false',
    minInputValue = '3',
    maxInputValue = '100',
    borderColorValue = 'rgba(122, 127, 133, 1)',
    focusValue = 'rgba(186, 202, 247, 1)',
    backgroundColorValue = 'rgba(255, 255, 255, 1)',
    attributeIdValue = 'AttributeId',
    maximumValueInput = '500',
    trueValue = 'true',
    numericInputVal = '10',
    placeHolderValue = 'placeholder',
    maxNumericInputValue = '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890',
    lowerLetterInputValue = 'abcdefghijklmn',
    upperLetterInputValue = 'ABCDEFGHIJKLMN',
    textAreaPlaceholderName = 'Bio...'
}
