export enum Locators {
    iframe = '#storybook-preview-iframe',
    pinentryComponent = '[class="nexus-center-xs nexus-mt-5"]>nexus-pin-entry',
    pinentryInput = '[class="nexus-center-xs nexus-mt-5"]>nexus-pin-entry>div>nexus-input>input',
    toggle = '[class="css-ozs5u1"]',
    lengthTextbox = '[name="length"]',
    type = '[class="css-1h8u63y"]',
    pinentryVR = '.sto-10ro1m',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-pin-entry',
    radioComponentLocator = '#component-form-elements-pin-entry',
    disabledSideMenu = '#component-form-elements-pin-entry--b-disabled',
    withLengthSideMenu = '#component-form-elements-pin-entry--c-with-custom-length',
    lengthMinInputValue = '1',
    lengthMaxInputValue = '7',
    lengthInputValue = '6',
    lengthMidInputValue = '3',
    AttributeTextValue = 'text',
    AttributeTypeValue = 'type',
    AttributeLengthValue = 'length',
    AttributeMaxLengthValue = 'maxlength',
    AttributePasswordValue = 'password',
    AttributeTelValue = 'tel',
  }
