export enum Locators {
    iframe = '#storybook-preview-iframe',
    checkbox = '[class="nexus-checkbox nexus-checkbox-label-wrap"]>div',
    checkboxInput = '[class="nexus-checkbox nexus-checkbox-label-wrap"]>input',
    checkedcheckboxinputBox = '[class="nexus"]>nexus-checkbox>label>input',
    checkBoxInputCheckedState = '[class="nexus-checkbox nexus-checkbox-label-wrap nexus-checkbox-checked"]>input',
    exampleCheckedCheckbox = '[class="nexus"]>div>nexus-checkbox>label>input',
    checkedCheckbox = '[class="nexus-checkbox nexus-checkbox-label-wrap nexus-checkbox-checked"]>div',
    checkboxText = '[class="nexus-checkbox nexus-checkbox-label-wrap"]>span',
    aatrIdTextbox = '[class="css-141ccx4"]',
    nexusCheckBox = '[class="nexus"]>nexus-checkbox',
    checkedToggle = '[name="checked"]',
    disabledToggle = '[name="disabled"]',
    indeterminateToggle = '[name="indeterminate"]',
    requiredToggle = '[name="required"]',
    checkboxBackground = '[class="nexus-checkbox nexus-checkbox-label-wrap"]>div>nexus-icon>svg]',
    checkCheckbox = '[class="nexus"]>div>nexus-checkbox>label>input',
    checkCheckboxLabel = '[class="nexus"]>div>nexus-checkbox>label>span',
    checkBoxVR = '[class="sto-u3ub1n"]',
    HideButton = '[class="nexus-center-xs nexus-mt-2"]>button',
    goToFullScreen = '[class="sto-102is01"]>button',
    hideAddOn = '[class="sto-l698cp"]',
    Checked = "Checked",
    Disabled = "Disabled",
    configDefault = '[id="check1"]>label>input',
    configChecked = '[id="check1"]>label>input',
    configIndeterminateChecked = '[id="indeterminate1"]>label>input',
    configIndeterminateExampleChecked = '[id="example1"]>label>input',
    configDisabled = '[id="disable1"]>label>input',
    configEnabled = '[id="disable1"]>label>input',
    configunchecked = '[id="check1"]>label>input',
    configIndeterminateUnChecked = '[id="indeterminate1"]>label>input',
    configDisabledChecked = '[id="disable1"]>label>input',
    checkConfig = '#component-form-elements-checkbox--b-configuration',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-checkbox',
    checkboxComponentLocator = '#component-form-elements-checkbox',
    checkConfigSideMenu = '[id="component-form-elements-checkbox--b-configuration"]'
}