export enum Locators {
    iframe = '#storybook-preview-iframe',
    errorMessage = '[class="nexus-error-message"]',
    errorMessageIcon = '[class="nexus-error-message"]>nexus-icon',
    firstNameLabel = '[class="nexus-form-field hydrated nexus-invalid"]>nexus-label>label',
    errorTextBox = '[class="nexus-form-field hydrated nexus-invalid"]>nexus-input>input',
    messageTextBox = '[class="css-14m39zm"]>table>tbody>tr>td>label>textarea',
    errorVR = '[class="sto-u3ub1n"]',
    emailValidationSideMenu = '#component-form-elements-error-message--b-email-validation',
    nameValidationSideMenu = '#component-form-elements-error-message--c-name-validation',
    enterYourEmailTextbox = '[class="nexus-form-field hydrated"]>nexus-input>input',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-error-message',
    errorComponentLocator = '#component-form-elements-error-message',
    pleaseProvideEmailLabel = '[class="nexus-form-field hydrated"]>nexus-label>label',
    EnterFirstNameValue = 'Please enter a first name.',
    IncorrectErroressageValue = 'Incorrect values entered leads to an error message',
    CustomisedErrorValue = 'Customised Error Message',
    ProvideEmailValue = 'Please provide your email address',
    EmailIdValue = 'validemailid@gmail.com',
    EnterNameValue = 'Enter Your Name',
    MaxTenLettersValue = 'Max_10_Letters',
    MaxLengthValue = '10',
    NumericValue = '1234567890',
    NumericMaxValue = '12345678901234567890',
    redColorValue = 'rgb(218, 53, 16)',
    EnterEmailValue = 'EnterYourEmail'
 }
