export enum Locators {
    iframe = '#storybook-preview-iframe',
    radioVR = '[class="sto-u3ub1n"]',
    radioOption = '[class="nexus-center-xs nexus-mt-5"]>div>nexus-radio',
    radioOptionRadioButton = '[class="nexus-center-xs nexus-mt-5"]>div>nexus-radio>label>input',
    radioOptionText = '[class="nexus-center-xs nexus-mt-5"]>div>nexus-radio>label>span',
    groupOption = '[class="nexus-col-xs-1"]>nexus-radio',
    groupRadioButton = '[class="nexus-col-xs-1"]>nexus-radio>label>input',
    groupText = '[class="nexus-col-xs-1"]>nexus-radio>label>span',
    selectFrameworkLabel = '[class="nexus-col-xs "]>nexus-label>label',
    withIconOption = '[class="nexus-row nexus-center-xs"]>nexus-radio',
    withIconRadioButton = '[class="nexus-row nexus-center-xs"]>nexus-radio>label>input',
    withIconText = '[class="nexus-row nexus-center-xs"]>nexus-radio>label>span',
    withIconIcon = '[class="nexus-row nexus-center-xs"]>nexus-radio>label>span>nexus-icon',
    agreementToTermLabel = '[class="nexus"]>nexus-card>div',
    agreementLabel = '[class="nexus"]>nexus-card>div>div>p',
    agreementToabel = '[class="nexus"]>nexus-card>div>div>p>strong',
    agreementTermLabel = '[class="nexus"]>nexus-card>div>div>p',
    variantsOption = '[class="nexus-col-xs-1"]>nexus-radio',
    variantsOptionRadioButton = '[class="nexus-col-xs-1"]>nexus-radio>label>input',
    variantsOptionText = '[class="nexus-col-xs-1"]>nexus-radio>label>span',
    variantsGroupNameLabel = '[class="nexus"]>div>div>nexus-label',
    groupDisabledOption = '[class="nexus-center-xs nexus-mt-5"]>div>nexus-radio',
    groupDisabledOptionRadioButton = '[class="nexus-center-xs nexus-mt-5"]>div>nexus-radio>label>input',
    groupDisabledOptionText = '[class="nexus-center-xs nexus-mt-5"]>div>nexus-radio>label>span',
    disabledSelectedOption = '[class="nexus-center-xs nexus-mt-5"]>div>section>nexus-radio',
    disabledSelectedOptionRadioButton = '[class="nexus-center-xs nexus-mt-5"]>div>section>nexus-radio>label>input',
    disabledSelectedOptionText = '[class="nexus-center-xs nexus-mt-5"]>div>section>nexus-radio>label>span',
    attrIdTextbox = '[name="attrId"]',
    ToggleButton = '[class="css-ozs5u1"]',
    nameTextbox = '[name="name"]',
    radioGroupSideMenu = '#component-form-elements-radio--b-group',
    radioWithIconSideMenu = '#component-form-elements-radio--c-with-icon',
    radioVariantsSideMenu = '#component-form-elements-radio--d-variants',
    radioGroupDisabledSideMenu = '#component-form-elements-radio--e-group-disabled',
    radioDisabledSelectedSideMenu = '#component-form-elements-radio--f-disabled-selected',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-radio',
    radioComponentLocator = '#component-form-elements-radio',
    radioComponentSideMenu = '#component-form-elements-radio--a-radio',
    optionOneValue = 'Option 1',
    optionTwoValue = 'Option 2',
    optionThreeValue = 'Option 3',
    firstOptionValue = 'option1',
    secondOptionValue = 'option2',
    ThirdOptionValue = 'option3',
    firstOption = 'option 3',
    secondOption = 'option 2',
    thirdOption = 'option 1',
    firstOptionTextValue = 'Option1',
    secondOptionTextValue = 'Option2',
    thirdOptionTextValue = 'Option3',
    checkedValue = 'checked',
    checkedValueOption = 'Checked',
    disabledValue = 'disabled',
    disabledValueOption = 'Disabled',
    requiredValue = 'required',
    radioValue = 'radio',
    reactValue = 'React',
    angularValue = 'Angular',
    vueValue = 'Vue',
    selectFraneworkValue = 'Select framework:',
    acceptTermsValue = 'Accept Terms and Conditions.',
    donotAcceptTermsValue = 'Don\'t accept terms and conditions.',
    withIconValue = 'withIcon',
    acceptTermsInnerTextValue = 'These Terms and Conditions of Use (the "Terms of Use") apply to the Nexus web site located at www.Nexus.com, and all associated sites linked to www.Nexus.com by Nexus, its subsidiaries and affiliates, including Nexus sites around the world (collectively, the "Site"). The Site is the property of Nexus Inc. ("Nexus") and its licensors. BY USING THE SITE, YOU AGREE TO THESE TERMS OF USE; IF YOU DO NOT AGREE, DO NOT USE THE SITE.Nexus reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms of Use, Nexus grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.',
    defaultValue = 'Default',
    checkedAndDisabledValue = 'Checked and Disabled',
    attributeIdValue = 'AttributeID',
    simpleRadioValueOptionOne = 'Simple Radio Example for Option 1',
    simpleRadioValueOptionTwo = 'Simple Radio Example for Option 2',
}
