export enum locators {
    accordionHeader = '[class="banner nexus-pl-4 nexus-mb-2"] .nexus-h3',
    header = 'Accordion',
    accordionTextLoc = '[class="nexus-pt-4 nexus-body-sm"] .nexus-body.primary-story',
    accordionText = 'Component used to store any content that can be expanded or collapsed',
    accordionDefault = 'div#story--component-layout-accordion--a-accordion nexus-accordion#acc-default > .hydrated > .nexus-accordion-trigger',
    accordionDefaultIcon = 'div#story--component-layout-accordion--a-accordion nexus-accordion#acc-default > .hydrated  .nexus-accordion-icons > nexus-icon:nth-of-type(1) > svg',
    iframe = '#storybook-preview-iframe',
    accordionVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-navigation',
    COMPONENT_NAME = '#component-navigation-accordion',
    accordionComponentLocator = '#component-navigation-accordion--a-accordion',
    accordionSideMenu = '#component-navigation-accordion--a-accordion',
    statusSideMenu = '#component-navigation-accordion--b-status',
    accordionComponent = '[class="nexus"]>div>nexus-accordion',
    accordionStatusAttribute = 'status',
    defaultaccordionType = 'row',
    defaultaccordionTypeAttribute = 'accordiontype',
    accordionIndividualComponent = '[class="nexus"]>div>nexus-accordion>nav>ol>nexus-accordion-item',
    accordionComponentIcon = '[class="nexus"]>div>nexus-accordion>nav>ol>nexus-accordion-item>div>nexus-icon',
    accordionComponentCircleIcon = '[class="nexus"]>div>nexus-accordion>nav>ol>nexus-accordion-item>div>nexus-icon circle',
    accordionIconComponent = '[class="nexus"]>div>nexus-accordion>nav>ol>nexus-accordion-item>div>div',
    accordionComponentLabel = '[class="nexus"]>div>nexus-accordion>nav>ol>nexus-accordion-item>div>button',
    featureSetComponentLabel = '[class="nexus"]>div>nexus-accordion>nav>ol>nexus-accordion-item>div>a',
    titleAttribute = 'title',
    cxAttribute = 'cx',
    cyAttribute = 'cy',
    rAttribute = 'r',
    fallAttribute = 'fill',
    accordionLG = 'lg',
    accordionMD = 'md',
    accordionSM = 'sm',
    accordionXL = 'xl',
    accordionXS = 'xs',
    circleValue = '12',
    GreenValue = '#44AB46',
    bindColorValue = '#fff',
    sourceDataLabel = 'Source data',
    dataExplorationLabel = 'Data exploration',
    featureSetsLabel = 'Feature sets',
    trainingLabel = 'Training',
    testAnalysisLabel = 'Test & analysis',
    createJourneyLabel = 'Create Journey',
    addedJourneyLabel = 'Added Journey Step',
    bindActionsToActivityLabel = 'Bind actions to activity',
    linkActivityToJourneyStepLabel = 'Link activity to journey step',
    activateLabel = 'Activate',
    stepCountOne = 'step1',
    stepCountTwo = 'step',
    stepCountThree = 'step3',
    stepCountFour = 'step4',
    stepCountFive = 'step5',
    dataExplorationTitle = '2',
    featureSetsTitle = '3',
    testAnalysisTitle = '5',
    accordionTypeSelectBox = '[id="control-accordiontype"]',
    rowLabel = 'row',
    columnLabel = 'column',
}
