export enum Locators {
    iframe = '#storybook-preview-iframe',
    inputVR = '[class="sto-u3ub1n"]',
    goToFullScreen = '[class="sto-102is01"]>button',
    hideAddOn = '[class="sto-l698cp"]',
    inputLabel = '[class="nexus"]>nexus-form-field>nexus-label>label',
    inputTextBox = '[class="nexus-form-field hydrated"]>nexus-input',
    inputTextBoxDisabled = '[class="nexus-form-field hydrated nexus-disabled"]>nexus-input',
    inputTextBoxInput = '[class="nexus-form-field hydrated"]>nexus-input>input',
    inputTextBoxInvalid = '[class="nexus-form-field hydrated nexus-invalid"]>nexus-input>input',
    control = '[class="css-14m39zm"]>table>tbody>tr>td>label>textarea',
    controltoggle = '[class="css-14m39zm"]>table>tbody>tr>td>label',
    controlSelect = '[class="css-14m39zm"]>table>tbody>tr>td>span>select',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-input',
    inputComponentLocator = '#component-form-elements-input',
    inputSideMenu = '#component-form-elements-input--a-input',
    inputMaxLength = '#component-form-elements-input--b-max-length',
    inputPasswordSideMenu = '#component-form-elements-input--c-with-password',
    inputWithNumberSideMenu = '#component-form-elements-input--d-with-number',
    inputWithDateSideMenu = '#component-form-elements-input--e-with-date',
    inputWithReadOnlySideMenu = '#component-form-elements-input--f-read-only',
    inputWithDisabledSideMenu = '#component-form-elements-input--g-disabled',
    errorMessage = '[class="nexus-error-message"]>nexus-icon',
    firstNameValue = 'First name',
    whiteColorValue = 'rgb(0, 0, 0)',
    typeValue = 'type',
    textValue = 'text',
    requiredValue = 'required',
    minLengthValue = 'min-length',
    maxLengthValue = 'max-length',
    lengthValue = '10',
    disabledValue = 'disabled',
    minInputValue = '0',
    maxInputValue = '1235678907364716497469',
    attributeIdValue = 'AttributeID',
    maximumValue = '50',
    dateValue = 'date',
    emailValue = 'email',
    numberValue = 'number',
    passwordValue = 'password',
    telValue = 'tel',
    placeHolderValue = 'PlaceholderEnteredNow',
    inputFieldLabelValue = 'Input Field Example (max-length=20)',
    NumericInputValue = '20',
    NumericCombinationValue = '12345678901234567890',
    MinimumLengthValue = '1234567890',
    numericValue = 'numeric',
    alphabetValue = 'alphabet',
    lowerCaseValue = 'lowerCase',
    upperCaseValue = 'upperCase',
    alphanumericValue = 'alphanumeric',
    specialCharactersValue = 'specialCharacters',
    minValue = 'minimum Value',
    maxValue = 'maximum value',
    numericVariantValue = '123567890',
    alphabetInputValue = 'abcdefghijabcdefghij',
    upperCaseInputValue = 'CAPITALLETTERS',
    alphanumericInputValue = 'abcdef1234',
    specialCharacterInputValue = '!@#$%^&*()_-+=|;:\'<,',
    numericCombinationInput = '123567890',
    singleValue = 'a',
    numericValueCombination = '123567890123567890',
    passwordFieldExampleValue = 'Password Field Example',
    yourPasswordValue = 'YourPassword',
    passwordLabelValue = 'password',
    passwordInputValue = 'Password@1234',
    onlyNumbersAllowedValue = 'Only number is allowed',
    valueLabel = 'Value...',
    numberLabelValue = 'number',
    combinationNumericValie = '1234567890',
    decimalCombinationValue = '123.78787',
    datefieldLabel = 'Date Field Example (Min 2022-01-01 and Max 2023-01-01)',
    inputDate = '2022-01-01',
    dateLabelValue = 'date',
    inputDateCombination = '2026-01-01',
    dateCombination = '2023-01-01',
    readyOnlyLabel = 'Readonly Field Example',
    readOnlyPlaceholder = 'ThisisReadOnlyField',
    readOnlyvalue = 'readonly',
    disabledLabelValue = 'Disabled Field Example',
    FieldDisabledValue = 'TheFieldIsDisabled',
    disabledVlaue = 'disabled',
 }
