export enum Locators {
    iframe = '#storybook-preview-iframe',
    menuVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-navigation',
    COMPONENT_NAME = '#component-navigation-menu--a-menu',
    menuComponentLocator = '#component-navigation-menu--a-menu',
    menuButtonComponent = '[id="trigger1"]',
    openMenuText = 'Open Menu',
    menuListComponent = '[class="nexus-menu-list"]>nexus-menu-item>div>a',
    itemOne = 'Item 1',  
    itemTwo = 'Item 2',  
    itemThree = 'Item 3',
    menuHref = 'javascript:void(0)',
    closeMenu = '[id="menu1"]',
    closeButton = '[class="nexus-btn nexus-btn-icon"]>nexus-icon>svg',
    trueValue = 'true',
    falseValue = 'false',
    closedClass = 'nexus-menu nexus-menu-right hydrated',
    openedClass = 'nexus-menu nexus-menu-right hydrated nexus-menu-open',
    openToggleButton = '[id="control-open"]',
    positionSelectBox = '[id="control-position"]',  
    leftValue = 'left',
    rightValue = 'right',
    topValue = 'top',
    backgroundBlackColor =  'rgb(72, 74, 76)',
    openAttribute = 'open',
    positionAttribute = 'position'
}
