export enum Locators {
    iframe = '#storybook-preview-iframe',
    toggleVR = '[class="sto-u3ub1n"]',
    toggleSlider = '[class="nexus-toggle-align-center"]>label>span',
    toggle = '[id="stdToggle"]',
    toggleInput = '[class="nexus-toggle-align-center"]>label>input',
    toggleIcon = '[class="nexus-toggle-align-center"]>span',
    toggleDisabled = '[class="nexus-toggle hydrated"]',
    toggleDisabledIcon = '[class="nexus-toggle-align-center"]>label',
    toggleButtonSlider = '[class="nexus-toggle hydrated"]>div>label>span',
    toggleLabel = '[class="nexus-toggle-labels nexus-toggle-label-right"]',
    toggleInActive = '[class="nexus-toggle-labels nexus-toggle-label-left nexus-toggle-label-selected"]',
    toggleDisabledSideMenu = '[id="component-form-elements-toggle--b-disabled"]',
    toggleWithLabelSideMenu = '[id="component-form-elements-toggle--c-with-label"]',
    toggleButtonSideMenu = '[id="component-form-elements-toggle--d-type-button"]',
    toggleSwitchSizeSideMenu = '[id="component-form-elements-toggle--e-switch-size"]',
    toggleButtonSizeSideMenu = '[id="component-form-elements-toggle--f-button-size"]',
    toggleButton = '[class="nexus-toggle hydrated"]',
    toggleButtonInput = '[class="nexus-toggle-align-center nexus-toggle-button-wrapper"]>label>input',
    toggleButtonLabel = '[class="nexus-toggle-align-center nexus-toggle-button-wrapper"]>span',
    toggleSideMenu = '[id="component-form-elements-toggle--a-toggle"]',
    controlAttrID = '[name="attrId"]',
    controlLabelActive = '[name="labelActive"]',
    controlLabelInActive = '[name="labelInactive"]',
    controlSize = '[id="control-size"]',
    controlType = '[id="control-type"]',
    controlDisabled = '[id="control-disabled"]',
    controlRequired = '[id="control-required"]',
    controlToggled = '[id="control-toggled"]',
    extraSmallLabel = 'Extra Small',
    smallLabel = 'Small',
    mediumLabel= 'Medium',
    largeLabel = 'Large',
    extraLargeLabel = 'Extra Large',
    extraSmallvalue = 'xs',
    smallValue = 'sm',
    mediumValue = 'md',
    largeValue = 'lg',
    extraLargeValue = 'xl',
    typeSwitchLabel = 'Type Switch',
    typeButtonLabel = 'Type Button',
    switchValue = 'switch',
    buttonValue = 'button',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-toggle',
    toggleComponentLocator = '#component-form-elements-toggle',
    size = 'size',
    type = 'type',
    toggled = 'toggled',
    sizeValue = 'md',
    typeValue = 'switch',
    toggledValue = 'false',
    typeInputValue = 'checkbox',
    disabledValue = 'disabled',
    ariaChecked = 'aria-checked',
    false = 'false',
    true = 'true',
    labelInActive = 'label-inactive',
    labelInActiveValue = 'hide',
    labelActive = 'label-active',
    labelActiveValue = 'show',
    attributeIdValue = 'AttributeId',
    labelActiveLabel = 'LabelActive',
    labelInactiveLabel = 'LabelInActive',
    required = 'required',
    defaultBackgroundColor = 'rgb(0, 0, 0)',
    orangeBackgroundColor = 'rgb(255, 135, 51)',
}
