export enum Locators {
    iframe = '#storybook-preview-iframe',
    headerVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-navigation',
    COMPONENT_NAME = '#component-navigation-header',
    headerComponentLocator = '#component-navigation-header--a-header',
    headercomponentMobile = '[class="nexus-container"]>div>nexus-header-menu>button>nexus-icon',
    headerComponent = '[class="nexus-header-sticky nexus-header hydrated"]>div>div',
    headerLogo = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-logo',
    headerNexusLabel = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-logo>a>nexus-icon tspan',
    headerNexusIconSymbol = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-logo>a>nexus-icon>svg>g',
    headerMenuComponent = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu',
    headerMenuList = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div',
    headerMenuItemComponent = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item',
    headerMenuItem = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item>div>a',
    headerWithAvatarSideMenu = '#component-navigation-header--b-with-avatar',
    headerWithAvatar = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item>div>nexus-avatar',
    avatarImg = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item>div>nexus-avatar>div>img',
    avatarImgIntials = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item>div>nexus-avatar>div>span',
    avatarImgStatus = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item>div>nexus-avatar>div>div',
    avatarImgName = '[class="nexus-header-sticky nexus-header hydrated"]>div>div>nexus-header-menu>nexus-menu>nav>div>nexus-menu-item>div>nexus-avatar>span',
    nexusLabel = 'NEXUS',
    fontSizeLabel =  'font-size',
    fontfamilyLabel =  'font-family',
    fontWeightLabel =  'font-weight',
    letterSpacingLabel =  'letter-spacing',
    fontSizeValue =  '28',
    fontfamilyValue =  'Helvetica',
    fontWeightValue =  'normal',
    letterSpacingValue =  '4.42105263',
    backgroundOrangeColor =  'rgb(255, 135, 51)',
    backgroundGreenColor =  'rgb(89, 209, 89)',
    itemOneLabel = 'item 1',
    itemTwoLabel = 'item 2',
    itemThreeLabel = 'item 3',
    itemOneValue = 'Item 1',
    itemTwoValue = 'Item 2',
    itemThreeValue = 'Item 3',
    homeHeader = 'Home',
    dashboardHeader = 'Dashboard',
    avatarValue = 'Jane Doe',
    avatarInitialsLabel = 'JD',
    headerLinkValue = 'javascript:void(0)',
    avatarClass = 'avatar-image',
    avatarSrc = './assets/images/avatar.png',
    avatarStatusClass = 'avatar-status-lg avatar-status avatar-status-online',
}
