export enum Locators {
    iframe = '#storybook-preview-iframe',
    formFieldVR = '[class="sto-u3ub1n"]',
    formFieldInputBox = '[class="nexus-form-field hydrated"]>nexus-input>input',
    formFieldDisabledInputBox = '[class="nexus-form-field hydrated nexus-disabled"]>nexus-input',
    formFieldWithMessage = '[class="nexus-form-field hydrated"]>nexus-input',
    formFieldMessage = '[class="nexus-form-field hydrated"]>nexus-message',
    formFieldErrorMessageTextbox = '[class="nexus-form-field hydrated nexus-invalid"]>nexus-input',
    formFieldErrorMessage = '[class="nexus-form-field hydrated nexus-invalid"]>nexus-error-message',
    formFieldLabel ='[class="nexus-form-field hydrated"]>nexus-label>label',
    formFieldDisabledLabel = '[class="nexus-form-field hydrated nexus-disabled"]>nexus-label>label',
    formFieldWithMessageLabel = '[class="nexus-form-field hydrated"]>nexus-label>label',
    formFieldWithErrorLabel = '[class="nexus-form-field hydrated nexus-invalid"]>nexus-label>label',
    disabledSideMenu = '#component-form-elements-form-field--b-disabled',
    withMessageSideMenu = '#component-form-elements-form-field--c-with-message',
    withErrorSideMenu = '#component-form-elements-form-field--d-with-error',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-form-field',
    formfieldComponentLocator = '#component-form-elements-form-field',
    firstNameValue = 'First Name',
    borderColorValue = 'rgb(122, 127, 133)',
    numericVariant = 'numeric',
    alphabetVariant = 'alphabet',
    lowerCaseVariant = 'lowerCase',
    upperCaseVariant = 'upperCase',
    alphanumericVariant = 'alphanumeric',
    specialCharactersVariant = 'specialCharacters',
    minimumValueVariant = 'minimum Value',
    maximumValueVariant = 'maximum value',
    numericValue = '1235678907364716497469',
    alphabeticValue = 'abcdefghijklmnopqrstuvwxyz',
    lowerCaseValue = 'smallletters',
    upperCsseValue = 'CAPITALLETTERS',
    alphanumericValue = 'abcdef1234',
    specialCharactersValue = '!@#$%^&*()_-+=|;:\'<,',
    minimumValue = 'a',
    maximumValue = '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890',
    disabledModalValue = 'Disabled Modal',
    disabledValue = 'disabled',
    customMessageValue = 'Custom Message',
    ErrorMessageError = 'This is an error message'
 }
