export enum Locators {
  iframe = '#storybook-preview-iframe',
  paginationComponent = '[class="nexus"]>div>nexus-pagination',
  paginationButton = '[class="nexus"]>div>nexus-pagination>button',
  paginationCount = '[class="nexus"]>div>nexus-pagination>div',
  paginationCountInput = '[class="nexus"]>div>nexus-pagination>div>input',
  pageCount = '[class="nexus-pagination-count-input"]',
  currentTextBox = '[name="current"]',
  maxTextBox = '[name="max"]',
  paginationVR = '.sto-10ro1m',
  CATEGORY = '#component-buttons-and-indicators',
  COMPONENT_NAME = '#component-buttons-and-indicators-pagination--a-pagination',
  paginationComponentLocator = '#component-buttons-and-indicators-pagination--a-pagination',
  minValue = '3',
  maxValue = '5',
  firstPageValue = 'First Page',
  previousPageValue = 'Previous Page',
  nextPageValue = 'Next Page',
  lastPageValue = 'Last Page',
  minimumValue = '1',
  maximumValue = '100',
}
