export enum Locators {
    iframe = '#storybook-preview-iframe',
    progressbarComponent = '[class="nexus"]>div>nexus-progress-bar',
    progressComponent = '[class="nexus"]>div>nexus-card>nexus-card-body>div>div>nexus-progress-bar',
    toggle = '[class="css-ozs5u1"]',
    progressbarCircleComponent = '[class="nexus"]>div>nexus-progress-bar>div>div',
    progressbarValue = '[name="value"]',
    infiniteProgressbarComponent = '[class="nexus"]>div>nexus-progress-bar',
    checkETA = '[class="nexus"]>div>button',
    reportComponent = '[class="nexus"]>div>nexus-card',
    systemPerformanceTitle = '[class="nexus"]>div>nexus-card>div>div>div>nexus-card-header>nexus-card-header-title',
    reportElement = '[class="nexus"]>div>nexus-card>nexus-card-body>div>div',
    progressBarVR = '.sto-10ro1m',
    CATEGORY = '#component-buttons-and-indicators',
    COMPONENT_NAME = '#component-buttons-and-indicators-progress-bar',
    progressbarComponentLocator = '#component-buttons-and-indicators-progress-bar',
    progressbarInfinite = '#component-buttons-and-indicators-progress-bar--b-infinite',
    progressbarReports = '#component-buttons-and-indicators-progress-bar--c-reports',
    progressbarError = '[class="nexus"]>nexus-progress-bar>div>[class ="nexus-progress-bar-right-side nexus-progress-bar-half-circle"]',
    falseValue = 'false',
    circleValue = 'circle',
    indeterminateValue = 'indeterminate',
    errorValue = 'error',
    value = 'value',
    inputValue = '50',
    trueValue = 'true',
    transformRotateValue = 'transform: rotate(180deg);',
    valueInput = '100',
    checkEtaValue = 'Check ETA',
    calculationEtaValue = 'Calculating ETA',
    systemPerformanceValue = 'System Performance',
    processorValue = 'Processor',
    memoryValue = 'Memory',
    graphicsValue = 'Graphics',
    primaryHddValue = 'Primary HDD',
    circleValueOne = '75',
    circleValueTwo = '85',
    circleValueThree = '65',
    circelValueFour = '25',
}
