export enum Locators {
    iframe = '#storybook-preview-iframe',
    badge = '[class="nexus-center-xs nexus-mt-5"]>nexus-badge',
    badgeComponent = '[class="sto-u3ub1n"]',
    badgeComponentID = '[id="component-buttons-and-indicators-badge"]',
    MobileTab = '[class="sto-4t3mb0"]>button',
    hideAddOn = '[class="sto-l698cp"]',
    goToFullScreen = '[class="sto-102is01"]>button',
    badgeMenu = '#component-buttons-and-indicators-badge',
    sideMenuMobile = '[class="sto-4t3mb0"]>button',
    overlap = '[name="overlap"]',
    variant = '[class="css-1h8u63y"]',
    variantDropdown = '#control-variant',
    label = '[class="css-k008qs"]>textarea',
    Button = '[class="nexus-center-xs nexus-mt-5"]>button',
    badgeAppearanceButton = '[class="nexus-col-xs-4 nexus-center-xs"]',
    overlapBadge = '[class="nexus-badge nexus-badge-overlap nexus-badge-default nexus-badge-has-content hydrated"]',
    icon = '[class="nexus-btn nexus-btn-icon"]',
    errorIcon = '[class="nexus-badge nexus-badge-overlap nexus-badge-error nexus-badge-has-content hydrated"]',
    successIcon = '[class="nexus-badge nexus-badge-overlap nexus-badge-success nexus-badge-has-content hydrated"]',
    warnIcon = '[class="nexus-badge nexus-badge-overlap nexus-badge-warning nexus-badge-has-content hydrated"]',
    defaultIcon = '[class="nexus-badge nexus-badge-overlap nexus-badge-default nexus-badge-has-content hydrated"]',
    defaultBadgeLabel = '[class="nexus-row nexus-mt-1 nexus-mt-1"]>div>div>div>span',
    defaultBadge = '[class="nexus-col-xs-1"]>nexus-badge>span',
    defaultBadgeClass = '[class="nexus-badge nexus-badge-default nexus-badge-has-content hydrated"]',
    sideBar = '[class="sto-4t3mb0"]>button',
    canvas = '[class="sto-1lyqzqv"]>a>button',
    badgeAppearance = '[class="nexus"]>div',
    badgeButtonOverlay = '[class="nexus-center-xs nexus-mt-5"]',
    menuAppearance = '[class="sto-79elbk"]>a',
    menuButtonOverlay = '[id="component-buttons-and-indicators-badge--c-button-overlay"]',
    menuIconOverlay = '[id="component-buttons-and-indicators-badge--d-icon-overlay"]',
    parameter = 'parameter',
    badgeComponentLocator = '#component-buttons-and-indicators-badge',
    appearence = '#component-buttons-and-indicators-badge--b-appearence',
    overlay = '#component-buttons-and-indicators-badge--c-button-overlay',
    iconOverlay = '#component-buttons-and-indicators-badge--d-icon-overlay',
    buttonOverlay = '#component-buttons-and-indicators-badge--c-button-overlay',
    CATEGORY = '#component-buttons-and-indicators',
    COMPONENT_NAME = '#component-buttons-and-indicators-badge',
    variantError = 'error',
    variantSuccess = 'success',
    variantWarning = 'warning',
    variantDefault = 'default',
    variantDanger = 'danger',
    defaultbgcolor = 'rgb(45, 46, 47)',
    errorbgcolor = 'rgb(218, 53, 16)',
    successbgcolor = 'rgb(89, 209, 89)',
    warningbgcolor = 'rgb(255, 195, 0)',
    defaultText = 'Sample Text',
    BadgeText = 'Badge Sample Label',
    clickText = 'Click me!\nNew',
    attrTrue = 'true',
    attrFalse= 'false',
    txtNew = 'New',
    txtNumSingle = '1',
    txtNumDouble = '99',
    txtNumTriple = '999',
    txtNumTetra = '9999',
    defaultValue = 'Default',
    successValue = 'Success',
    warningValue = 'Warning',
    dangerValue = 'Danger'
}
