export enum Locators {
    iframe = '#storybook-preview-iframe',
    searchComponent = '[class="nexus"]>nexus-search>nexus-input',
    searchInput = '[class="nexus"]>nexus-search>nexus-input>input',
    searchIcon = '[class="nexus"]>nexus-search>nexus-input>nexus-icon',
    searchList = '[class="nexus"]>nexus-search>nexus-search-list',
    debounceInterval = '[name="debounceInterval"]',
    MobileTab = '[class="sto-4t3mb0"]>button',
    searchVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-search--a-search',
    searchComponentLocator = '#component-form-elements-search--a-search',
    autoCompleteAttribute = 'autocomplete',
    offAttributeValue = 'off',
    typeAttribute = 'type',
    textAttributeValue = 'text',
    backgroundColorAttribute = 'background-color',
    colorAttribute = 'color',
    deBounceIntervalValue = '3000',
    whiteColorValue = 'rgba(0, 0, 0, 0)',
    blackColorValue = 'rgb(0, 0, 0)',
    orangeColorValue = 'rgb(255, 135, 51)',
    numericInputValue = '12345678901234567890',
    alphabeticLowerCaseInputValue = 'abcdefghijklmn',
    alphabeticUpperCaseInputValue = 'ABCDEFGHIJKLMN',
    alphabeticAlphanumericInputValue = 'abcdef1234',
    minimumInputValue = 'a',
    maximumInputValue = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    specialCharactersInputValue = '!@#$%^&*()_-+=|;:',
    numericLabel = 'Numeric',
    lowerCaseLabel = 'lower case',
    upperCaseLabel = 'upper case',
    alphanumericLabel = 'Alphanumeric',
    minimumLengthLabel = 'Minimum Length',
    maximumLengthLabel = 'Maximum Length',
    specialCharactersLabel = 'special Characters',
}
