/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@nexus/core';

import { applyPolyfills, defineCustomElements } from '@nexus/core/loader';

applyPolyfills().then(() => defineCustomElements());
export const NexusAccordion = /*@__PURE__*/createReactComponent<JSX.NexusAccordion, HTMLNexusAccordionElement>('nexus-accordion');
export const NexusAccordionContent = /*@__PURE__*/createReactComponent<JSX.NexusAccordionContent, HTMLNexusAccordionContentElement>('nexus-accordion-content');
export const NexusAccordionGroup = /*@__PURE__*/createReactComponent<JSX.NexusAccordionGroup, HTMLNexusAccordionGroupElement>('nexus-accordion-group');
export const NexusAccordionTrigger = /*@__PURE__*/createReactComponent<JSX.NexusAccordionTrigger, HTMLNexusAccordionTriggerElement>('nexus-accordion-trigger');
export const NexusAvatar = /*@__PURE__*/createReactComponent<JSX.NexusAvatar, HTMLNexusAvatarElement>('nexus-avatar');
export const NexusBadge = /*@__PURE__*/createReactComponent<JSX.NexusBadge, HTMLNexusBadgeElement>('nexus-badge');
export const NexusBarChart = /*@__PURE__*/createReactComponent<JSX.NexusBarChart, HTMLNexusBarChartElement>('nexus-bar-chart');
export const NexusBreadcrumb = /*@__PURE__*/createReactComponent<JSX.NexusBreadcrumb, HTMLNexusBreadcrumbElement>('nexus-breadcrumb');
export const NexusBreadcrumbItem = /*@__PURE__*/createReactComponent<JSX.NexusBreadcrumbItem, HTMLNexusBreadcrumbItemElement>('nexus-breadcrumb-item');
export const NexusCard = /*@__PURE__*/createReactComponent<JSX.NexusCard, HTMLNexusCardElement>('nexus-card');
export const NexusCardAvatar = /*@__PURE__*/createReactComponent<JSX.NexusCardAvatar, HTMLNexusCardAvatarElement>('nexus-card-avatar');
export const NexusCardBody = /*@__PURE__*/createReactComponent<JSX.NexusCardBody, HTMLNexusCardBodyElement>('nexus-card-body');
export const NexusCardBodyImage = /*@__PURE__*/createReactComponent<JSX.NexusCardBodyImage, HTMLNexusCardBodyImageElement>('nexus-card-body-image');
export const NexusCardFooter = /*@__PURE__*/createReactComponent<JSX.NexusCardFooter, HTMLNexusCardFooterElement>('nexus-card-footer');
export const NexusCardHeader = /*@__PURE__*/createReactComponent<JSX.NexusCardHeader, HTMLNexusCardHeaderElement>('nexus-card-header');
export const NexusCardHeaderButton = /*@__PURE__*/createReactComponent<JSX.NexusCardHeaderButton, HTMLNexusCardHeaderButtonElement>('nexus-card-header-button');
export const NexusCardHeaderDetails = /*@__PURE__*/createReactComponent<JSX.NexusCardHeaderDetails, HTMLNexusCardHeaderDetailsElement>('nexus-card-header-details');
export const NexusCardHeaderSubtitle = /*@__PURE__*/createReactComponent<JSX.NexusCardHeaderSubtitle, HTMLNexusCardHeaderSubtitleElement>('nexus-card-header-subtitle');
export const NexusCardHeaderTitle = /*@__PURE__*/createReactComponent<JSX.NexusCardHeaderTitle, HTMLNexusCardHeaderTitleElement>('nexus-card-header-title');
export const NexusCarousel = /*@__PURE__*/createReactComponent<JSX.NexusCarousel, HTMLNexusCarouselElement>('nexus-carousel');
export const NexusCarouselItem = /*@__PURE__*/createReactComponent<JSX.NexusCarouselItem, HTMLNexusCarouselItemElement>('nexus-carousel-item');
export const NexusCharts = /*@__PURE__*/createReactComponent<JSX.NexusCharts, HTMLNexusChartsElement>('nexus-charts');
export const NexusCheckbox = /*@__PURE__*/createReactComponent<JSX.NexusCheckbox, HTMLNexusCheckboxElement>('nexus-checkbox');
export const NexusChip = /*@__PURE__*/createReactComponent<JSX.NexusChip, HTMLNexusChipElement>('nexus-chip');
export const NexusChipGroup = /*@__PURE__*/createReactComponent<JSX.NexusChipGroup, HTMLNexusChipGroupElement>('nexus-chip-group');
export const NexusDropdown = /*@__PURE__*/createReactComponent<JSX.NexusDropdown, HTMLNexusDropdownElement>('nexus-dropdown');
export const NexusErrorMessage = /*@__PURE__*/createReactComponent<JSX.NexusErrorMessage, HTMLNexusErrorMessageElement>('nexus-error-message');
export const NexusFileUpload = /*@__PURE__*/createReactComponent<JSX.NexusFileUpload, HTMLNexusFileUploadElement>('nexus-file-upload');
export const NexusFooter = /*@__PURE__*/createReactComponent<JSX.NexusFooter, HTMLNexusFooterElement>('nexus-footer');
export const NexusFooterBottom = /*@__PURE__*/createReactComponent<JSX.NexusFooterBottom, HTMLNexusFooterBottomElement>('nexus-footer-bottom');
export const NexusFooterColumn = /*@__PURE__*/createReactComponent<JSX.NexusFooterColumn, HTMLNexusFooterColumnElement>('nexus-footer-column');
export const NexusFooterContent = /*@__PURE__*/createReactComponent<JSX.NexusFooterContent, HTMLNexusFooterContentElement>('nexus-footer-content');
export const NexusFooterContentTitle = /*@__PURE__*/createReactComponent<JSX.NexusFooterContentTitle, HTMLNexusFooterContentTitleElement>('nexus-footer-content-title');
export const NexusFooterLogo = /*@__PURE__*/createReactComponent<JSX.NexusFooterLogo, HTMLNexusFooterLogoElement>('nexus-footer-logo');
export const NexusFormField = /*@__PURE__*/createReactComponent<JSX.NexusFormField, HTMLNexusFormFieldElement>('nexus-form-field');
export const NexusHeader = /*@__PURE__*/createReactComponent<JSX.NexusHeader, HTMLNexusHeaderElement>('nexus-header');
export const NexusHeaderLogo = /*@__PURE__*/createReactComponent<JSX.NexusHeaderLogo, HTMLNexusHeaderLogoElement>('nexus-header-logo');
export const NexusHeaderMenu = /*@__PURE__*/createReactComponent<JSX.NexusHeaderMenu, HTMLNexusHeaderMenuElement>('nexus-header-menu');
export const NexusIcon = /*@__PURE__*/createReactComponent<JSX.NexusIcon, HTMLNexusIconElement>('nexus-icon');
export const NexusInput = /*@__PURE__*/createReactComponent<JSX.NexusInput, HTMLNexusInputElement>('nexus-input');
export const NexusLabel = /*@__PURE__*/createReactComponent<JSX.NexusLabel, HTMLNexusLabelElement>('nexus-label');
export const NexusLineChart = /*@__PURE__*/createReactComponent<JSX.NexusLineChart, HTMLNexusLineChartElement>('nexus-line-chart');
export const NexusLoader = /*@__PURE__*/createReactComponent<JSX.NexusLoader, HTMLNexusLoaderElement>('nexus-loader');
export const NexusMenu = /*@__PURE__*/createReactComponent<JSX.NexusMenu, HTMLNexusMenuElement>('nexus-menu');
export const NexusMenuItem = /*@__PURE__*/createReactComponent<JSX.NexusMenuItem, HTMLNexusMenuItemElement>('nexus-menu-item');
export const NexusMessage = /*@__PURE__*/createReactComponent<JSX.NexusMessage, HTMLNexusMessageElement>('nexus-message');
export const NexusModal = /*@__PURE__*/createReactComponent<JSX.NexusModal, HTMLNexusModalElement>('nexus-modal');
export const NexusModalBody = /*@__PURE__*/createReactComponent<JSX.NexusModalBody, HTMLNexusModalBodyElement>('nexus-modal-body');
export const NexusModalFooter = /*@__PURE__*/createReactComponent<JSX.NexusModalFooter, HTMLNexusModalFooterElement>('nexus-modal-footer');
export const NexusModalHeader = /*@__PURE__*/createReactComponent<JSX.NexusModalHeader, HTMLNexusModalHeaderElement>('nexus-modal-header');
export const NexusModalHeaderSubtitle = /*@__PURE__*/createReactComponent<JSX.NexusModalHeaderSubtitle, HTMLNexusModalHeaderSubtitleElement>('nexus-modal-header-subtitle');
export const NexusNotification = /*@__PURE__*/createReactComponent<JSX.NexusNotification, HTMLNexusNotificationElement>('nexus-notification');
export const NexusOption = /*@__PURE__*/createReactComponent<JSX.NexusOption, HTMLNexusOptionElement>('nexus-option');
export const NexusPagination = /*@__PURE__*/createReactComponent<JSX.NexusPagination, HTMLNexusPaginationElement>('nexus-pagination');
export const NexusPieChart = /*@__PURE__*/createReactComponent<JSX.NexusPieChart, HTMLNexusPieChartElement>('nexus-pie-chart');
export const NexusPinEntry = /*@__PURE__*/createReactComponent<JSX.NexusPinEntry, HTMLNexusPinEntryElement>('nexus-pin-entry');
export const NexusProgressBar = /*@__PURE__*/createReactComponent<JSX.NexusProgressBar, HTMLNexusProgressBarElement>('nexus-progress-bar');
export const NexusProgressBarLabel = /*@__PURE__*/createReactComponent<JSX.NexusProgressBarLabel, HTMLNexusProgressBarLabelElement>('nexus-progress-bar-label');
export const NexusRadio = /*@__PURE__*/createReactComponent<JSX.NexusRadio, HTMLNexusRadioElement>('nexus-radio');
export const NexusSearch = /*@__PURE__*/createReactComponent<JSX.NexusSearch, HTMLNexusSearchElement>('nexus-search');
export const NexusSearchList = /*@__PURE__*/createReactComponent<JSX.NexusSearchList, HTMLNexusSearchListElement>('nexus-search-list');
export const NexusSearchListItem = /*@__PURE__*/createReactComponent<JSX.NexusSearchListItem, HTMLNexusSearchListItemElement>('nexus-search-list-item');
export const NexusSelect = /*@__PURE__*/createReactComponent<JSX.NexusSelect, HTMLNexusSelectElement>('nexus-select');
export const NexusSlider = /*@__PURE__*/createReactComponent<JSX.NexusSlider, HTMLNexusSliderElement>('nexus-slider');
export const NexusStackedBarChart = /*@__PURE__*/createReactComponent<JSX.NexusStackedBarChart, HTMLNexusStackedBarChartElement>('nexus-stacked-bar-chart');
export const NexusStepper = /*@__PURE__*/createReactComponent<JSX.NexusStepper, HTMLNexusStepperElement>('nexus-stepper');
export const NexusStepperItem = /*@__PURE__*/createReactComponent<JSX.NexusStepperItem, HTMLNexusStepperItemElement>('nexus-stepper-item');
export const NexusTabBar = /*@__PURE__*/createReactComponent<JSX.NexusTabBar, HTMLNexusTabBarElement>('nexus-tab-bar');
export const NexusTable = /*@__PURE__*/createReactComponent<JSX.NexusTable, HTMLNexusTableElement>('nexus-table');
export const NexusTextarea = /*@__PURE__*/createReactComponent<JSX.NexusTextarea, HTMLNexusTextareaElement>('nexus-textarea');
export const NexusToast = /*@__PURE__*/createReactComponent<JSX.NexusToast, HTMLNexusToastElement>('nexus-toast');
export const NexusToggle = /*@__PURE__*/createReactComponent<JSX.NexusToggle, HTMLNexusToggleElement>('nexus-toggle');
export const NexusTooltip = /*@__PURE__*/createReactComponent<JSX.NexusTooltip, HTMLNexusTooltipElement>('nexus-tooltip');
export const NexusTooltipContent = /*@__PURE__*/createReactComponent<JSX.NexusTooltipContent, HTMLNexusTooltipContentElement>('nexus-tooltip-content');
export const NexusTooltipTrigger = /*@__PURE__*/createReactComponent<JSX.NexusTooltipTrigger, HTMLNexusTooltipTriggerElement>('nexus-tooltip-trigger');
export const NexusTree = /*@__PURE__*/createReactComponent<JSX.NexusTree, HTMLNexusTreeElement>('nexus-tree');
export const NexusTreeContent = /*@__PURE__*/createReactComponent<JSX.NexusTreeContent, HTMLNexusTreeContentElement>('nexus-tree-content');
export const NexusTreeTrigger = /*@__PURE__*/createReactComponent<JSX.NexusTreeTrigger, HTMLNexusTreeTriggerElement>('nexus-tree-trigger');
