export enum Locators {
    iframe = '#storybook-preview-iframe',
    avatarVR = '[class="sto-u3ub1n"]',
    avatarComponent = '[class="nexus"]>nexus-avatar',
    avtarIcon = '[class="nexus"]>nexus-avatar>div>span',
    avtarLabel = '[class="nexus"]>nexus-avatar>span',
    avatarSizeLabel = '[class="nexus-col-xl-2"]>p',
    avatarSizeIcon = '[class="nexus-col-xl-2"]>nexus-avatar',
    avatarStatusLabel = '[class="nexus-col-xl-8"]>p',
    avatarStatusIcon = '[class="nexus-col-xl-8"]>nexus-avatar',
    avatarStatusIcons = '[class="nexus-col-xl-8"]>nexus-avatar>div',
    avatarStatusIconLabel = '[class="nexus-col-xl-8"]>nexus-avatar>div>span',
    avatarStatusIconOnline = '[class="nexus-col-xl-8"]>nexus-avatar>div>div',
    avatarImageName = '[class="nexus-col-xl-8"]>nexus-avatar>span',
    avatarImage = '[class="nexus-col-xl-8"]>nexus-avatar>div>img',
    avatarNotifications = '[class="nexus-col-xl-8"]>nexus-avatar>div>div>span',
    avatarNexusIcon = '[class="nexus-col-xl-8"]>nexus-avatar>div>nexus-icon',
    control = '[class="css-14m39zm"]>table>tbody>tr>td>label>textarea',
    controltoggle = '[class="css-14m39zm"]>table>tbody>tr>td>label',
    CATEGORY = '#component-form-elements',
    COMPONENT_NAME = '#component-form-elements-avatar',
    avatarComponentLocator = '#component-form-elements-avatar',
    avatarSideMenu = '#component-form-elements-avatar--a-avatar',
    avatarSizeSideMenu = '#component-form-elements-avatar--b-size',
    avatarStatusSideMenu = '#component-form-elements-avatar--c-status',
    avatarImageNameSideMenu = '#component-form-elements-avatar--d-image-and-name',
    avatarInitialNameSideMenu = '#component-form-elements-avatar--e-initial-and-name',
    avatarInitialNameNotifSideMenu = '#component-form-elements-avatar--f-initial-name-and-notification',
    avatarInitialSideMenu = '#component-form-elements-avatar--g-initials',
    avatrLogoNameSideMenu = '#component-form-elements-avatar--h-logo-and-name',
    avatarNNValue = 'NN',
    avatarNoNameValue = 'No Name',
    avatarStatusValue = 'avatar-status',
    userNameValue = 'user-name',
    classNameValue = 'classname',
    imageValue = 'img',
    logoValue = 'logo',
    testValue = 'test',
    statusValue = 'status',
    newNameValue = 'new name',
    avatarClassNameValue = 'avatar-class-name',
    avatarImgValue = 'avatar-image-src',
    avatarLogoValue = 'avatar-logo-icon',
    avatarNotificationValue = 'avatar-notification',
    avatarSizeValue = 'avatar-size',
    avatarXSValue = 'xs',
    avatarSMValue = 'sm',
    avatarMDValue = 'md',
    avatarLGValue = 'lg',
    avatarXLValue = 'xl',
    avatarWithStatusValue = 'Avatar with Status',
    onlineValue = 'online',
    avatarNameDisplayValue = 'avatar-name-display',
    falseValue = 'false',
    trueValue = 'true',
    JBValue = 'JB',
    avatarImageNameValue = 'Avatar with Image and Name',
    avatarJBValue = 'Joseph Benjamin',
    avatarInitialsNameValue = 'Avatar with Initials and Name',
    avatarInitialNameNotificationValue = 'Avatar with Initials, Name and Notification',
    avatarWithInitialsValue = 'Avatar with Initials',
    avatarLogoNameValue = 'Avatar with Logo and Name',
    avatarNumericValue = '14',
    avatarDarkValue = 'avatar-dark'
  }
