export enum Locators {
    iframe = '#storybook-preview-iframe',
    stepperVR = '[class="sto-u3ub1n"]',
    CATEGORY = '#component-navigation',
    COMPONENT_NAME = '#component-navigation-stepper',
    stepperComponentLocator = '#component-navigation-stepper--a-stepper',
    stepperSideMenu = '#component-navigation-stepper--a-stepper',
    statusSideMenu = '#component-navigation-stepper--b-status',
    stepperComponent = '[class="nexus"]>div>nexus-stepper',
    stepperStatusAttribute = 'status',
    defaultStepperType = 'row',
    defaultStepperTypeAttribute = 'steppertype',
    stepperIndividualComponent = '[class="nexus"]>div>nexus-stepper>nav>ol>nexus-stepper-item',
    stepperComponentIcon = '[class="nexus"]>div>nexus-stepper>nav>ol>nexus-stepper-item>div>nexus-icon',
    stepperComponentCircleIcon = '[class="nexus"]>div>nexus-stepper>nav>ol>nexus-stepper-item>div>nexus-icon circle',
    stepperIconComponent = '[class="nexus"]>div>nexus-stepper>nav>ol>nexus-stepper-item>div>div',
    stepperComponentLabel = '[class="nexus"]>div>nexus-stepper>nav>ol>nexus-stepper-item>div>button',
    featureSetComponentLabel = '[class="nexus"]>div>nexus-stepper>nav>ol>nexus-stepper-item>div>a',
    titleAttribute = 'title',
    cxAttribute = 'cx',
    cyAttribute = 'cy',
    rAttribute = 'r',
    fallAttribute = 'fill',
    stepperCompleted = 'completed',
    stepperComplete = 'complete',
    stepperWarning = 'warning',
    stepperActive = 'active',
    stepperDefault = 'default',
    stepperError = 'error',
    circleValue = '12',
    GreenValue = '#44AB46',
    bindColorValue = '#fff',
    sourceDataLabel = 'Source data',
    dataExplorationLabel = 'Data exploration',
    featureSetsLabel = 'Feature sets',
    trainingLabel = 'Training',
    testAnalysisLabel = 'Test & analysis',
    createJourneyLabel = 'Create Journey',
    addedJourneyLabel = 'Added Journey Step',
    bindActionsToActivityLabel = 'Bind actions to activity',
    linkActivityToJourneyStepLabel = 'Link activity to journey step',
    activateLabel = 'Activate',
    stepCountOne = 'step1',
    stepCountTwo = 'step',
    stepCountThree = 'step3',
    stepCountFour = 'step4',
    stepCountFive = 'step5',
    dataExplorationTitle = '2',
    featureSetsTitle = '3',
    testAnalysisTitle = '5',
    stepperTypeSelectBox = '[id="control-steppertype"]',
    rowLabel = 'row',
    columnLabel = 'column',
}
