export enum Locators {
    iframe = '#storybook-preview-iframe',
    dropdownVR = '[class="sto-u3ub1n"]',
    dropdownHeader = '.banner > .nexus-h3',
    header = ' Dropdown',
    dropdownIcon = '#dropdownId',
    dropdownTextLoc = '#story--component-navigation-dropdown--a-dropdown > div > div > div > p',
    dropdownText = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint Lorem ipsum dolor sit consectetur',
    dropdownList = '.nexus-dropdown-container',
    hidecode = '.docblock-code-toggle',
    CATEGORY = '#component-navigation',
    COMPONENT_NAME = '#component-navigation-dropdown',
    dropdownComponentLocator = '#component-navigation-dropdown',
    height = 'height',
    heightValue = '300',
    width = 'width',
    widthValue = '400',
    typeBasicValue = 'basic',
    typeSelectValue = 'Select',
    dropdownTypeSelect = '#control-dropdownType',
    placementSelect = '#control-placement',
    placementCenterValue = 'center',
    placementRightValue = 'right',
    placementLeftValue = 'left',
    controlShow = '#control-show',
    text = 'text',
    withButtonPrim = '.nexus-flex-row > button.nexus-btn-primary',
    withButtonSec = '.nexus-flex-row > button.nexus-btn-warn',
    withButtonPrimColor = '#484a4c',
    withButtonSecColor = '#da3510',
    primOptsList = '#nexus-select-1',
    secOptsList = 'nexus-select-2',
    addValue = 'add',
    blockValue = 'block',
    primaryOptionsValue = 'Primary Options',
    deleteValue = 'delete',
    saveValue = 'save',
    loadValue = 'load',
    secondaryOptionsValue = 'Secondary Options',
    editValue = 'edit',
    dropdownIconRight = 'nexus-dropdown [placement="right"]',
    dropdownListRight = '#dropdownId > div > div.nexus-dropdown-container.nexus-dropdown-active'

}